// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCliffIP02kf8lHYnnvyOgo22LylMuIUOU',
    appId: '1:523558182407:web:88bab2c9f2d9d85c7a54a2',
    messagingSenderId: '523558182407',
    projectId: 'alba-health-app',
    authDomain: 'alba-health-app.firebaseapp.com',
    storageBucket: 'alba-health-app.firebasestorage.app',
    measurementId: 'G-142K4FL702',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSmO3lDpC8eraBOeqqZVzLzgnBlvywuuM',
    appId: '1:523558182407:android:c267c767abd5a9b77a54a2',
    messagingSenderId: '523558182407',
    projectId: 'alba-health-app',
    storageBucket: 'alba-health-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAzaNtq_tMvfRTnJWzk0Lb-7IpwtUwg5g',
    appId: '1:523558182407:ios:ccf3bae65981c2b87a54a2',
    messagingSenderId: '523558182407',
    projectId: 'alba-health-app',
    storageBucket: 'alba-health-app.firebasestorage.app',
    iosBundleId: 'com.example.proyectoAlbaGuatemala',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAzaNtq_tMvfRTnJWzk0Lb-7IpwtUwg5g',
    appId: '1:523558182407:ios:ccf3bae65981c2b87a54a2',
    messagingSenderId: '523558182407',
    projectId: 'alba-health-app',
    storageBucket: 'alba-health-app.firebasestorage.app',
    iosBundleId: 'com.example.proyectoAlbaGuatemala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCliffIP02kf8lHYnnvyOgo22LylMuIUOU',
    appId: '1:523558182407:web:4cda928d33a66db57a54a2',
    messagingSenderId: '523558182407',
    projectId: 'alba-health-app',
    authDomain: 'alba-health-app.firebaseapp.com',
    storageBucket: 'alba-health-app.firebasestorage.app',
    measurementId: 'G-56RCYXQTK0',
  );
}
